/* ============================================================
   SQL-Arena — Inhalte: Seed-DB, SQL-Aufgaben, Quiz/Match-Pools
   ============================================================ */
const SEED_DB = {
  KUNDE: [
    {kunde_id:1, name:'Anna Berger', ort:'Graz', plz:'8010'},
    {kunde_id:2, name:'Tom Fischer', ort:'Wien', plz:'1010'},
    {kunde_id:3, name:'Lena Huber', ort:'Graz', plz:'8020'},
    {kunde_id:4, name:'Max Novak', ort:'Linz', plz:'4020'},
    {kunde_id:5, name:'Nina Kogler', ort:'Wien', plz:'1030'},
    {kunde_id:6, name:'Paul Steiner', ort:'Salzburg', plz:'5020'},
  ],
  ARTIKEL: [
    {artikel_id:1, bezeichnung:'USB-Kabel', preis:9.90, kategorie:'Zubehör', lagerbestand:50},
    {artikel_id:2, bezeichnung:'Maus', preis:19.90, kategorie:'Zubehör', lagerbestand:30},
    {artikel_id:3, bezeichnung:'Monitor', preis:199.00, kategorie:'Hardware', lagerbestand:5},
    {artikel_id:4, bezeichnung:'Tastatur', preis:39.50, kategorie:'Zubehör', lagerbestand:0},
    {artikel_id:5, bezeichnung:'Laptop', preis:899.00, kategorie:'Hardware', lagerbestand:3},
    {artikel_id:6, bezeichnung:'Kopfhörer', preis:59.00, kategorie:'Zubehör', lagerbestand:18},
  ],
  BESTELLUNG: [
    {bestellung_id:1, kunde_id:1, datum:'2026-01-05', status:'geliefert'},
    {bestellung_id:2, kunde_id:2, datum:'2026-01-06', status:'offen'},
    {bestellung_id:3, kunde_id:1, datum:'2026-02-01', status:'offen'},
    {bestellung_id:4, kunde_id:3, datum:'2026-02-10', status:'geliefert'},
    {bestellung_id:5, kunde_id:5, datum:'2026-02-14', status:'storniert'},
  ],
  BESTELLPOSITION: [
    {bestellung_id:1, artikel_id:1, menge:2},
    {bestellung_id:1, artikel_id:3, menge:1},
    {bestellung_id:2, artikel_id:2, menge:3},
    {bestellung_id:3, artikel_id:4, menge:1},
    {bestellung_id:4, artikel_id:5, menge:1},
    {bestellung_id:4, artikel_id:6, menge:2},
    {bestellung_id:5, artikel_id:2, menge:1},
  ],
};

/* ---------- SQL-Spickzettel (immer sichtbare Referenz in der Werkstatt) ---------- */
const SQL_CHEATSHEET = [
  {t:'Spalten filtern', c:"SELECT spalte1, spalte2\nFROM TABELLE\nWHERE bedingung"},
  {t:'Text vergleichen', c:"WHERE ort = 'Graz'   -- Text IMMER in ' '"},
  {t:'Zahl vergleichen', c:"WHERE preis < 20     -- Zahlen OHNE ' '"},
  {t:'Sortieren & begrenzen', c:"ORDER BY preis DESC\nLIMIT 3"},
  {t:'Zwei Tabellen verknüpfen', c:"FROM A a\nJOIN B b ON a.id = b.a_id"},
  {t:'Auch Zeilen ohne Treffer', c:"FROM A a\nLEFT JOIN B b ON a.id = b.a_id"},
  {t:'Gruppieren & zählen', c:"SELECT spalte, COUNT(*) AS anzahl\nFROM TABELLE\nGROUP BY spalte"},
  {t:'Gruppen filtern', c:"GROUP BY spalte\nHAVING SUM(menge) > 100   -- nicht WHERE!"},
  {t:'Ohne Duplikate', c:"SELECT DISTINCT spalte FROM TABELLE"},
  {t:'Neue Zeile einfügen', c:"INSERT INTO TABELLE (spalte1, spalte2)\nVALUES (wert1, wert2)"},
  {t:'Werte ändern', c:"UPDATE TABELLE\nSET spalte = neuerWert\nWHERE bedingung   -- sonst ändert sich ALLES!"},
  {t:'Zeilen löschen', c:"DELETE FROM TABELLE\nWHERE bedingung   -- sonst wird ALLES gelöscht!"},
  {t:'Ergebnisse vereinen', c:"SELECT spalte FROM A\nUNION\nSELECT spalte FROM B   -- entfernt Duplikate"},
  {t:'Alles behalten', c:"... UNION ALL ...   -- wie UNION, aber MIT Duplikaten"},
  {t:'Schnittmenge / Differenz', c:"SELECT x FROM A INTERSECT SELECT x FROM B\nSELECT x FROM A EXCEPT SELECT x FROM B"},
  {t:'Join über gleiche Spalte', c:"FROM A JOIN B USING(gemeinsame_spalte)\n-- oder: FROM A NATURAL JOIN B"},
  {t:'Verschachtelte Abfrage (Skalar)', c:"WHERE preis > (SELECT AVG(preis) FROM ARTIKEL)"},
  {t:'IN mit Subquery', c:"WHERE kunde_id IN (SELECT kunde_id FROM BESTELLUNG)"},
  {t:'EXISTS / NOT EXISTS', c:"WHERE EXISTS (SELECT 1 FROM B WHERE b.a_id = a.id)\n-- prüft nur: gibt es Treffer?"},
  {t:'Gespeicherte Sicht (View)', c:"CREATE VIEW NAME AS\nSELECT ... FROM ...   -- nur lesbar, wie eine gespeicherte Abfrage"},
  {t:'Tabelle ändern/löschen', c:"ALTER TABLE T ADD COLUMN spalte TYP\nDROP TABLE T"},
];

/* ---------- SQL-Werkstatt Aufgaben ---------- */
// type:'select' -> Ergebnis wird per compareResults verglichen
// type:'write'   -> INSERT/UPDATE/DELETE, Tabellenzustand nach Ausführung wird verglichen
const SQL_TASKS_W5 = [
  {id:'s1', diff:1, type:'select', prompt:'Zeige die Spalten <b>name</b> und <b>ort</b> aller Kund*innen aus <b>Graz</b>.',
    sol:"SELECT name, ort FROM KUNDE WHERE ort = 'Graz'",
    hints:["Denk an WHERE für die Filterbedingung.", "Vergiss die Anführungszeichen bei Text nicht: 'Graz'."]},
  {id:'s2', diff:1, type:'select', prompt:'Zeige <b>bezeichnung</b> und <b>preis</b> aller Artikel, die weniger als 20&nbsp;€ kosten.',
    sol:"SELECT bezeichnung, preis FROM ARTIKEL WHERE preis < 20",
    hints:["WHERE preis < 20", "Ohne Anführungszeichen, weil preis eine Zahl ist."]},
  {id:'s3', diff:2, type:'select', prompt:'Zeige <b>bezeichnung</b> und <b>preis</b> der 3 teuersten Artikel — teuerster zuerst.',
    sol:"SELECT bezeichnung, preis FROM ARTIKEL ORDER BY preis DESC LIMIT 3",
    hints:["ORDER BY preis DESC sortiert absteigend.", "LIMIT 3 begrenzt auf drei Zeilen."], orderMatters:true},
  {id:'s4', diff:2, type:'select', prompt:'Zeige für jede Bestellung den <b>Kundennamen</b> (name) und das <b>Bestelldatum</b> (datum). Spalten in dieser Reihenfolge.',
    sol:"SELECT k.name, b.datum FROM KUNDE k JOIN BESTELLUNG b ON k.kunde_id = b.kunde_id",
    hints:["Ein JOIN zwischen KUNDE und BESTELLUNG über kunde_id.", "SELECT k.name, b.datum FROM KUNDE k JOIN BESTELLUNG b ON k.kunde_id = b.kunde_id"]},
  {id:'s5', diff:2, type:'select', prompt:'Welche Artikel (bezeichnung, menge) wurden in <b>Bestellung 1</b> bestellt?',
    sol:"SELECT a.bezeichnung, bp.menge FROM ARTIKEL a JOIN BESTELLPOSITION bp ON a.artikel_id = bp.artikel_id WHERE bp.bestellung_id = 1",
    hints:["JOIN ARTIKEL mit BESTELLPOSITION über artikel_id.", "Filtere zusätzlich mit WHERE bp.bestellung_id = 1."]},
  {id:'s6', diff:3, type:'select', prompt:'Zeige für jede Bestellposition: <b>Kundenname</b> (name), <b>Artikelbezeichnung</b> (bezeichnung), <b>Menge</b> (menge). Vier Tabellen sind nötig.',
    sol:"SELECT k.name, a.bezeichnung, bp.menge FROM KUNDE k JOIN BESTELLUNG b ON k.kunde_id = b.kunde_id JOIN BESTELLPOSITION bp ON b.bestellung_id = bp.bestellung_id JOIN ARTIKEL a ON bp.artikel_id = a.artikel_id",
    hints:["Kette: KUNDE → BESTELLUNG → BESTELLPOSITION → ARTIKEL.", "Drei JOINs hintereinander, jeweils über den passenden Fremdschlüssel."]},
  {id:'s7', diff:2, type:'select', prompt:'Zeige <b>kunde_id</b> und die <b>Anzahl</b> (als anzahl) der Bestellungen je Kunde — auch Kunden mit 0 Bestellungen sollen erscheinen.',
    sol:"SELECT k.kunde_id, COUNT(b.bestellung_id) AS anzahl FROM KUNDE k LEFT JOIN BESTELLUNG b ON k.kunde_id = b.kunde_id GROUP BY k.kunde_id",
    hints:["LEFT JOIN behält alle Kund*innen, auch ohne Treffer.", "GROUP BY k.kunde_id, dann COUNT(b.bestellung_id) — nicht COUNT(*), sonst zählt es leere Treffer mit!"]},
  {id:'s8', diff:3, type:'select', prompt:'Zeige <b>name</b> und den <b>Gesamtbestellwert</b> (als summe = menge × preis) je Kunde, aber nur Kund*innen mit einer Summe über 100. Sortiere absteigend nach summe.',
    sol:"SELECT k.name, SUM(bp.menge * a.preis) AS summe FROM KUNDE k JOIN BESTELLUNG b ON k.kunde_id = b.kunde_id JOIN BESTELLPOSITION bp ON b.bestellung_id = bp.bestellung_id JOIN ARTIKEL a ON bp.artikel_id = a.artikel_id GROUP BY k.name HAVING SUM(bp.menge * a.preis) > 100 ORDER BY summe DESC",
    hints:["Erst alle vier Tabellen verknüpfen wie zuvor.", "GROUP BY k.name, SUM(...) in HAVING filtert nach der Gruppensumme (nicht WHERE!)."], orderMatters:true},
  {id:'s9', diff:1, type:'select', prompt:'Aus welchen <b>Orten</b> (ort) kommen unsere Kund*innen — jeder Ort nur einmal?',
    sol:"SELECT DISTINCT ort FROM KUNDE",
    hints:["DISTINCT entfernt doppelte Zeilen aus dem Ergebnis."]},
  {id:'s10', diff:3, type:'select', prompt:'Zeige <b>name</b> (KUNDE) und <b>bestellung_id</b> für <b>alle</b> Kund*innen — auch jene ohne Bestellung (dann NULL bei bestellung_id).',
    sol:"SELECT k.name, b.bestellung_id FROM KUNDE k LEFT JOIN BESTELLUNG b ON k.kunde_id = b.kunde_id",
    hints:["Ein normaler JOIN würde Kund*innen ohne Bestellung weglassen.", "LEFT JOIN KUNDE → BESTELLUNG behält alle Kund*innen."]},
  {id:'s11', diff:2, type:'select', prompt:'Zeige <b>name</b> aller Kund*innen, die entweder aus <b>Graz</b> kommen <b>oder</b> mindestens eine <b>offene</b> Bestellung haben — jeder Name nur einmal (nutze <b>UNION</b>).',
    sol:"SELECT name FROM KUNDE WHERE ort = 'Graz' UNION SELECT k.name FROM KUNDE k JOIN BESTELLUNG b ON k.kunde_id = b.kunde_id WHERE b.status = 'offen'",
    hints:["Zwei separate SELECTs, verbunden mit UNION.", "UNION entfernt automatisch doppelte Zeilen (z.B. wenn jemand beide Bedingungen erfüllt)."]},
  {id:'s12', diff:2, type:'select', prompt:'Zeige <b>name</b> aller Kund*innen, die <b>mindestens eine</b> Bestellung aufgegeben haben. Nutze dafür eine <b>Subquery mit IN</b> (kein JOIN).',
    sol:"SELECT name FROM KUNDE WHERE kunde_id IN (SELECT kunde_id FROM BESTELLUNG)",
    hints:["WHERE kunde_id IN (SELECT kunde_id FROM BESTELLUNG)", "Die Subquery in Klammern liefert alle kunde_id, die in BESTELLUNG vorkommen."]},
  {id:'s13', diff:3, type:'select', prompt:'Zeige <b>name</b> aller Kund*innen, die <b>noch keine</b> Bestellung aufgegeben haben. Nutze <b>NOT EXISTS</b> mit einer korrelierten Subquery.',
    sol:"SELECT name FROM KUNDE k WHERE NOT EXISTS (SELECT 1 FROM BESTELLUNG b WHERE b.kunde_id = k.kunde_id)",
    hints:["NOT EXISTS (SELECT 1 FROM BESTELLUNG b WHERE b.kunde_id = k.kunde_id)", "Die innere Abfrage bezieht sich auf die äußere Zeile (k.kunde_id) — das macht sie 'korreliert'."]},
  {id:'s14', diff:3, type:'select', prompt:'Zeige <b>bezeichnung</b> und <b>preis</b> aller Artikel, die <b>teurer als der Durchschnittspreis</b> aller Artikel sind. Nutze eine <b>skalare Subquery</b>.',
    sol:"SELECT bezeichnung, preis FROM ARTIKEL WHERE preis > (SELECT AVG(preis) FROM ARTIKEL)",
    hints:["(SELECT AVG(preis) FROM ARTIKEL) liefert genau einen Wert — eine 'skalare' Subquery.", "WHERE preis > (SELECT AVG(preis) FROM ARTIKEL)"]},
  {id:'s15', diff:2, type:'select', prompt:'Zeige alle <b>kunde_id</b>, die <b>keine</b> Bestellung haben. Nutze <b>EXCEPT</b> (Menge aller Kund*innen minus Menge der bestellenden Kund*innen).',
    sol:"SELECT kunde_id FROM KUNDE EXCEPT SELECT kunde_id FROM BESTELLUNG",
    hints:["EXCEPT liefert alles aus der ersten Abfrage, was NICHT auch in der zweiten vorkommt.", "SELECT kunde_id FROM KUNDE EXCEPT SELECT kunde_id FROM BESTELLUNG"]},
  {id:'s16', diff:3, type:'createview', viewName:'OFFENE_BESTELLUNGEN', prompt:'Erstelle eine <b>View</b> namens <b>OFFENE_BESTELLUNGEN</b>, die <b>name</b> (KUNDE) und <b>datum</b> (BESTELLUNG) aller Bestellungen mit Status <b>\'offen\'</b> zeigt.',
    sol:"CREATE VIEW OFFENE_BESTELLUNGEN AS SELECT k.name, b.datum FROM KUNDE k JOIN BESTELLUNG b ON k.kunde_id = b.kunde_id WHERE b.status = 'offen'",
    hints:["CREATE VIEW NAME AS SELECT ...", "Die View speichert keine Daten, sondern die Abfrage selbst — bei jedem Zugriff neu berechnet."]},
  {id:'s17', diff:2, type:'write', table:'ARTIKEL', prompt:'Füge der Tabelle <b>ARTIKEL</b> eine neue Spalte <b>hersteller</b> (VARCHAR) mit Standardwert <b>\'unbekannt\'</b> hinzu.',
    sol:"ALTER TABLE ARTIKEL ADD COLUMN hersteller VARCHAR(50) DEFAULT 'unbekannt'",
    hints:["ALTER TABLE ARTIKEL ADD COLUMN hersteller VARCHAR(50) DEFAULT 'unbekannt'", "DEFAULT setzt den Wert für alle bereits vorhandenen Zeilen."]},
  {id:'s18', diff:2, type:'select', prompt:'Zeige <b>bestellung_id</b> und <b>artikel_id</b> aller Bestellpositionen — nutze diesmal <b>JOIN ... USING</b> statt ON (beide Tabellen haben die Spalte bestellung_id gemeinsam).',
    sol:"SELECT bestellung_id, artikel_id FROM BESTELLUNG JOIN BESTELLPOSITION USING(bestellung_id)",
    hints:["FROM BESTELLUNG JOIN BESTELLPOSITION USING(bestellung_id)", "USING(spalte) funktioniert nur, wenn beide Tabellen die Spalte gleich benennen — dann kein a.spalte = b.spalte nötig."]},
  {id:'s19', diff:1, type:'drop', table:'BESTELLPOSITION', prompt:'Die Tabelle <b>BESTELLPOSITION</b> wird nicht mehr gebraucht — <b>lösche</b> die ganze Tabelle (nicht nur die Zeilen!).',
    sol:"DROP TABLE BESTELLPOSITION",
    hints:["DELETE löscht nur Zeilen — die Tabelle selbst bleibt.", "DROP TABLE BESTELLPOSITION entfernt die ganze Tabelle inklusive Struktur."]},
];

const SQL_TASKS_W6 = [
  {id:'w1', diff:1, type:'write', table:'ARTIKEL', prompt:'Füge einen neuen Artikel ein: artikel_id 7, bezeichnung \'Webcam\', preis 45.00, kategorie \'Zubehör\', lagerbestand 12.',
    sol:"INSERT INTO ARTIKEL (artikel_id, bezeichnung, preis, kategorie, lagerbestand) VALUES (7, 'Webcam', 45.00, 'Zubehör', 12)",
    hints:["INSERT INTO ARTIKEL (spalten...) VALUES (werte...)", "Reihenfolge der Werte muss zur Spaltenliste passen."]},
  {id:'w2', diff:1, type:'write', table:'ARTIKEL', prompt:'Ändere den Preis von \'Maus\' auf 24.90.',
    sol:"UPDATE ARTIKEL SET preis = 24.90 WHERE bezeichnung = 'Maus'",
    hints:["UPDATE ARTIKEL SET preis = ... WHERE ...", "Ohne WHERE würden ALLE Artikel geändert!"]},
  {id:'w3', diff:2, type:'write', table:'ARTIKEL', prompt:'Erhöhe den Lagerbestand aller Artikel der Kategorie \'Zubehör\' um 10 (lagerbestand = lagerbestand + 10).',
    sol:"UPDATE ARTIKEL SET lagerbestand = lagerbestand + 10 WHERE kategorie = 'Zubehör'",
    hints:["SET lagerbestand = lagerbestand + 10", "WHERE kategorie = 'Zubehör' trifft mehrere Zeilen gleichzeitig."]},
  {id:'w4', diff:1, type:'write', table:'ARTIKEL', prompt:'Lösche alle Artikel, deren Lagerbestand 0 ist.',
    sol:"DELETE FROM ARTIKEL WHERE lagerbestand = 0",
    hints:["DELETE FROM ARTIKEL WHERE ...", "Ohne WHERE würde die GANZE Tabelle geleert!"]},
  {id:'w5', diff:2, type:'write', table:'BESTELLUNG', prompt:'Setze bei Bestellung 2 den Status auf \'geliefert\'.',
    sol:"UPDATE BESTELLUNG SET status = 'geliefert' WHERE bestellung_id = 2",
    hints:["UPDATE BESTELLUNG SET status = 'geliefert' WHERE bestellung_id = 2"]},
  {id:'w6', diff:2, type:'write', table:'BESTELLUNG', prompt:'Lösche alle Bestellungen mit Status \'storniert\'.',
    sol:"DELETE FROM BESTELLUNG WHERE status = 'storniert'",
    hints:["DELETE FROM BESTELLUNG WHERE status = 'storniert'"]},
  {id:'w7', diff:1, type:'write', table:'KUNDE', prompt:'Füge eine neue Kundin ein: kunde_id 7, name \'Julia Wagner\', ort \'Graz\', plz \'8010\'.',
    sol:"INSERT INTO KUNDE (kunde_id, name, ort, plz) VALUES (7, 'Julia Wagner', 'Graz', '8010')",
    hints:["INSERT INTO KUNDE (kunde_id, name, ort, plz) VALUES (...)"]},
];

/* ---------- Quiz-Pools je Welt (Speed-Quiz) ---------- */
const QUIZ = {
  w1: [
    {q:'Was ist eine Tabelle in einer relationalen Datenbank?', o:['Eine Sammlung von Zeilen mit gleicher Spaltenstruktur','Ein einzelner Wert','Ein Diagramm der Beziehungen','Eine Abfrage-Sprache'], c:0, e:'Eine Tabelle (Relation) besteht aus Zeilen (Datensätzen) mit denselben Spalten.'},
    {q:'Was beschreibt eine Zeile (auch: Tupel, Datensatz)?', o:['Die Struktur der Tabelle','Einen konkreten Datensatz mit je einem Wert pro Spalte','Den Tabellennamen','Eine Abfrage'], c:1, e:'Jede Zeile ist ein konkreter Datensatz.'},
    {q:'Wofür sorgt der Primärschlüssel (PK)?', o:['Er verknüpft zwei Tabellen','Er sortiert die Tabelle','Er identifiziert jede Zeile eindeutig','Er speichert Texte'], c:2, e:'Der Primärschlüssel ist die eindeutige, nicht-leere Kennung jeder Zeile.'},
    {q:'Was macht ein Fremdschlüssel (FK)?', o:['Er verweist auf den Primärschlüssel einer anderen Tabelle','Er verschlüsselt Daten','Er ist immer NULL','Er ersetzt den Primärschlüssel'], c:0, e:'Fremdschlüssel stellen Beziehungen zwischen Tabellen her.'},
    {q:'Was ist ein DBMS?', o:['Ein Diagrammtyp','Software zur Verwaltung von Datenbanken','Eine Abfragesprache','Ein Datentyp'], c:1, e:'DBMS = Datenbankmanagementsystem, z. B. MySQL, PostgreSQL.'},
    {q:'Was bedeutet NULL in einer Spalte?', o:['Der Wert 0','Ein Leerstring', 'Kein Wert vorhanden / unbekannt','Ein Fehler'], c:2, e:'NULL heißt "kein Wert", nicht 0 oder leer.'},
    {q:'Was ist ein Vorteil relationaler Datenbanken gegenüber einfachen Dateien?', o:['Sie brauchen keine Struktur','Strukturierte Abfragen, Konsistenz, weniger Redundanz','Sie sind immer schneller als jede Datei','Sie brauchen kein Schema'], c:1, e:'Relationale DBs bieten strukturierte Abfragen, Konsistenzregeln und Mehrbenutzerbetrieb.'},
    {q:'Was ist das "Schema" einer Datenbank?', o:['Ein Backup','Die Struktur: Tabellen, Spalten, Typen, Beziehungen','Eine einzelne Abfrage','Der Name des Servers'], c:1, e:'Das Schema beschreibt den Aufbau der Datenbank.'},
    {q:'Fachbegriff für "Tabelle"?', o:['Relation','Domäne','Kardinalität','Transaktion'], c:0, e:'"Relation" ist der Fachbegriff für Tabelle im relationalen Modell.'},
    {q:'Was ist eine Domäne (Attributdomäne)?', o:['Die Adresse des Servers','Die Menge der erlaubten Werte eines Attributs','Ein Fremdschlüssel','Eine Tabelle ohne Primärschlüssel'], c:1, e:'Die Domäne legt fest, welche Werte ein Attribut annehmen darf.'},
  ],
  w2: [
    {q:'Was ist eine Entität im ER-Modell?', o:['Eine Spalte','Ein eindeutig identifizierbares Objekt von Interesse, z. B. ein Kunde','Eine Abfrage','Ein Index'], c:1, e:'Entitäten sind die "Dinge", über die Daten gespeichert werden.'},
    {q:'Was ist eine Beziehung (Relationship) im ER-Modell?', o:['Ein Attribut','Eine Verbindung zwischen zwei oder mehr Entitäten','Ein Primärschlüssel','Ein Datentyp'], c:1, e:'Beziehungen verbinden Entitäten miteinander.'},
    {q:'"Ein Kunde hat mehrere Bestellungen, eine Bestellung gehört zu genau einem Kunden" — welche Kardinalität?', o:['1:1','1:n','n:m','0:0'], c:1, e:'Klassische 1:n-Beziehung.'},
    {q:'Wie wird eine n:m-Beziehung in Tabellen umgesetzt?', o:['Gar nicht möglich','Durch eine zusätzliche Verknüpfungstabelle mit zwei Fremdschlüsseln','Durch einen zusätzlichen Primärschlüssel','Durch NULL-Werte'], c:1, e:'n:m braucht eine eigene Tabelle mit FKs zu beiden Seiten.'},
    {q:'Was ist eine schwache Entität?', o:['Eine Entität ohne Attribute','Eine Entität, die nicht ohne eine andere (starke) Entität existieren kann','Eine Entität mit vielen Beziehungen','Eine gelöschte Entität'], c:1, e:'Schwache Entitäten hängen existenziell von einer starken Entität ab.'},
    {q:'Was zeigt ein ER-Diagramm?', o:['Nur SQL-Befehle','Entitäten, Attribute, Beziehungen und Kardinalitäten','Nur den Serverstandort','Ausschließlich Primärschlüssel'], c:1, e:'Das ER-Diagramm ist die grafische Modellierung der Datenstruktur.'},
    {q:'Wie wird eine 1:1-Beziehung meist umgesetzt?', o:['Verknüpfungstabelle','Fremdschlüssel (evtl. mit UNIQUE) in einer der beiden Tabellen','Gar nicht möglich','Zwei Primärschlüssel in einer Tabelle'], c:1, e:'Bei 1:1 reicht ein Fremdschlüssel, oft zusätzlich UNIQUE.'},
    {q:'"Eine Bestellung enthält mehrere Artikel, ein Artikel taucht in mehreren Bestellungen auf" — Kardinalität?', o:['1:1','1:n','n:m','Keine Beziehung'], c:2, e:'Beide Seiten "viele" → n:m, braucht Verknüpfungstabelle (z. B. Bestellposition).'},
    {q:'Was ist ein Attribut im ER-Modell?', o:['Eine Eigenschaft einer Entität, z. B. Name','Eine Beziehung','Eine Tabelle','Ein Fremdschlüssel'], c:0, e:'Attribute beschreiben die Eigenschaften einer Entität.'},
  ],
  w3: [
    {q:'Was ist das Ziel der Normalisierung?', o:['Mehr Redundanz erzeugen','Redundanz vermeiden und Anomalien verhindern','Tabellen zusammenführen','Abfragen verlangsamen'], c:1, e:'Normalisierung reduziert Redundanz und vermeidet Anomalien.'},
    {q:'Was fordert die 1. Normalform (1NF)?', o:['Atomare Werte, keine Wiederholungsgruppen','Keine transitive Abhängigkeit','Keine partielle Abhängigkeit','Genau eine Spalte pro Tabelle'], c:0, e:'1NF: jede Zelle enthält genau einen atomaren Wert.'},
    {q:'Was fordert die 2. Normalform (2NF) zusätzlich zur 1NF?', o:['Keine partielle Abhängigkeit vom (zusammengesetzten) Schlüssel','Keine NULL-Werte','Nur Zahlen als Attribute','Genau zwei Tabellen'], c:0, e:'2NF verlangt volle funktionale Abhängigkeit vom gesamten Primärschlüssel.'},
    {q:'Was fordert die 3. Normalform (3NF) zusätzlich?', o:['Keine transitive Abhängigkeit von Nicht-Schlüssel-Attributen','Keine Fremdschlüssel','Nur eine Zeile pro Tabelle','Keine Primärschlüssel'], c:0, e:'3NF: Nicht-Schlüssel-Attribute dürfen nicht von anderen Nicht-Schlüssel-Attributen abhängen.'},
    {q:'Was ist eine Einfügeanomalie?', o:['Man kann Daten nicht speichern, ohne unnötige andere Daten mit einzufügen','Man kann nichts löschen','Die Tabelle hat zu viele Spalten','Ein Tippfehler beim INSERT'], c:0, e:'Z. B. kann ein neuer Artikel nicht erfasst werden, ohne eine (unbekannte) Bestellung anzugeben.'},
    {q:'Was ist eine Änderungsanomalie (Update-Anomalie)?', o:['Ein Fakt ist mehrfach gespeichert und muss an mehreren Stellen geändert werden','Ein Update schlägt immer fehl','UPDATE ist in SQL nicht erlaubt','Der Primärschlüssel ändert sich automatisch'], c:0, e:'Redundante Daten müssen konsistent an mehreren Stellen aktualisiert werden.'},
    {q:'Was ist eine Löschanomalie?', o:['Beim Löschen einer Zeile gehen ungewollt weitere Informationen verloren','DELETE funktioniert nie','Es kann nichts gelöscht werden','Löschen dauert zu lange'], c:0, e:'Z. B. verschwindet der einzige Hinweis auf einen Kunden, wenn seine letzte Bestellung gelöscht wird.'},
    {q:'"A → B" (funktionale Abhängigkeit) bedeutet:', o:['A und B sind immer gleich','Der Wert von A bestimmt eindeutig den Wert von B','B bestimmt A','A und B sind unabhängig'], c:1, e:'Funktionale Abhängigkeit: zu jedem A-Wert gehört genau ein B-Wert.'},
    {q:'Warum ist "Ort hängt von PLZ ab, PLZ ist Nicht-Schlüssel-Attribut in der Kundentabelle" ein 3NF-Problem?', o:['Weil das eine transitive Abhängigkeit ist','Weil PLZ ein Primärschlüssel sein muss','Weil das 1NF verletzt','Es ist kein Problem'], c:0, e:'Ort hängt nicht direkt vom PK ab, sondern über PLZ — transitiv, verletzt 3NF.'},
  ],
  w4: [
    {q:'Wofür dient CREATE TABLE?', o:['Zum Löschen einer Tabelle','Zum Anlegen einer neuen Tabelle mit Spalten und Typen','Zum Einfügen von Daten','Zum Sortieren'], c:1, e:'CREATE TABLE definiert Name, Spalten, Datentypen und Constraints.'},
    {q:'Welcher Datentyp passt am besten für einen Geldbetrag mit Nachkommastellen?', o:['INT','DECIMAL','BOOLEAN','DATE'], c:1, e:'DECIMAL speichert exakte Nachkommastellen — wichtig bei Geldbeträgen.'},
    {q:'Wofür sorgt der PRIMARY KEY Constraint?', o:['Er erlaubt doppelte Werte','Er stellt Eindeutigkeit und NOT NULL für die Kennung sicher','Er verweist auf eine andere Tabelle','Er ist optional und meist leer'], c:1, e:'PRIMARY KEY = eindeutig + nicht leer.'},
    {q:'Wofür sorgt FOREIGN KEY?', o:['Referenzielle Integrität — verweist auf einen PK einer anderen Tabelle','Verschlüsselung','Sortierung','Datentyp-Umwandlung'], c:0, e:'FOREIGN KEY stellt sicher, dass der Verweis auf eine existierende Zeile zeigt.'},
    {q:'Wofür steht NOT NULL?', o:['Spalte darf leer bleiben','Spalte muss immer einen Wert enthalten','Spalte ist automatisch ein Schlüssel','Spalte akzeptiert nur Zahlen'], c:1, e:'NOT NULL verbietet leere Werte in dieser Spalte.'},
    {q:'Wofür steht UNIQUE?', o:['Werte in dieser Spalte dürfen sich nicht wiederholen','Spalte ist der Primärschlüssel','Spalte darf NULL sein, aber nur einmal','Spalte wird automatisch sortiert'], c:0, e:'UNIQUE erzwingt, dass kein Wert doppelt vorkommt.'},
    {q:'Merkmal von Single Table Inheritance (eine Tabelle für alle Subklassen)?', o:['Viele NULL-Felder, oft eine Diskriminator-Spalte für den Typ','Keine gemeinsame Tabelle','Jede Subklasse hat eine eigene komplette Tabelle','Keine Vererbung möglich'], c:0, e:'Alle Subklassen landen in einer breiten Tabelle mit vielen ungenutzten (NULL) Spalten.'},
    {q:'Merkmal von Table per Class (Concrete Table Inheritance)?', o:['Jede Subklasse bekommt eine eigene, vollständige Tabelle — gemeinsame Spalten werden dupliziert','Alles in einer Tabelle','Nur die Basisklasse hat eine Tabelle','Keine Duplizierung von Spalten'], c:0, e:'Jede konkrete Klasse hat ihre eigene komplette Tabelle, gemeinsame Spalten wiederholen sich.'},
    {q:'Merkmal von Joined Table Inheritance (Class Table Inheritance)?', o:['Basis- und Subklassen-Tabellen sind über den Primärschlüssel per JOIN verbunden','Es gibt nur eine einzige Tabelle','Keine Fremdschlüssel nötig','Subklassen brauchen keinen eigenen Schlüssel'], c:0, e:'Gemeinsame Attribute in der Basistabelle, spezifische in Subtabellen — verbunden per PK/FK-JOIN.'},
  ],
  w5: [
    {q:'Was liefert ein INNER JOIN?', o:['Nur Zeilen, die in beiden Tabellen einen Treffer haben','Alle Zeilen aus beiden Tabellen','Nur Zeilen der linken Tabelle','Nur die erste Zeile'], c:0, e:'INNER JOIN liefert nur "matching" Zeilen aus beiden Tabellen.'},
    {q:'Was liefert ein LEFT JOIN zusätzlich zum INNER JOIN?', o:['Alle Zeilen der linken Tabelle, auch ohne Treffer rechts (dann NULL)','Alle Zeilen der rechten Tabelle ohne Treffer','Gar nichts zusätzlich','Nur doppelte Zeilen'], c:0, e:'LEFT JOIN behält jede Zeile der linken Tabelle, fehlende rechte Werte werden NULL.'},
    {q:'Wofür steht die ON-Klausel bei einem JOIN?', o:['Sie sortiert das Ergebnis','Sie definiert die Verknüpfungsbedingung zwischen den Tabellen','Sie begrenzt die Zeilenanzahl','Sie benennt die Ausgabespalten'], c:1, e:'ON legt fest, welche Spalten gleich sein müssen, damit Zeilen verknüpft werden.'},
    {q:'Was macht UNION?', o:['Vereinigt die Ergebnisse zweier Abfragen und entfernt Duplikate','Verknüpft zwei Tabellen wie ein JOIN','Löscht Zeilen','Zählt Zeilen'], c:0, e:'UNION braucht gleiche Spaltenanzahl/-typen und liefert eindeutige Zeilen.'},
    {q:'Unterschied UNION vs. UNION ALL?', o:['UNION ALL behält Duplikate, UNION entfernt sie','Kein Unterschied','UNION ALL ist langsamer und macht dasselbe','UNION ALL funktioniert nur mit Zahlen'], c:0, e:'UNION ALL behält alle Zeilen inkl. Duplikate, UNION dedupliziert.'},
    {q:'Was ist eine VIEW?', o:['Eine physisch gespeicherte Kopie der Daten','Eine gespeicherte, benannte Abfrage, die wie eine Tabelle gelesen werden kann','Ein Backup der Datenbank','Ein Index'], c:1, e:'Eine View speichert keine eigenen Daten, sondern eine Abfrage-Definition.'},
    {q:'Wann ist eine View typischerweise NICHT schreibbar?', o:['Bei JOIN, GROUP BY, Aggregatfunktionen oder DISTINCT','Immer','Nie','Nur bei SELECT *'], c:0, e:'Sobald die View mehrere Tabellen oder Aggregationen kombiniert, ist meist kein eindeutiges UPDATE mehr möglich.'},
    {q:'Was bewirkt GROUP BY?', o:['Sortiert die Ausgabe','Fasst Zeilen mit gleichem Wert in den angegebenen Spalten zu Gruppen zusammen','Löscht doppelte Spalten','Erstellt eine neue Tabelle'], c:1, e:'GROUP BY wird meist zusammen mit Aggregatfunktionen wie COUNT, SUM verwendet.'},
    {q:'Unterschied WHERE vs. HAVING?', o:['WHERE filtert einzelne Zeilen vor der Gruppierung, HAVING filtert Gruppen nach der Gruppierung','Kein Unterschied','HAVING kommt vor WHERE','WHERE funktioniert nur mit Aggregatfunktionen'], c:0, e:'HAVING kann sich auf Aggregatwerte (z. B. SUM) beziehen, WHERE nicht.'},
  ],
  w6: [
    {q:'Wofür dient INSERT INTO?', o:['Zum Löschen von Zeilen','Zum Einfügen neuer Zeilen in eine Tabelle','Zum Ändern der Tabellenstruktur','Zum Sortieren'], c:1, e:'INSERT INTO fügt neue Datensätze ein.'},
    {q:'Was passiert bei UPDATE ohne WHERE?', o:['Nichts passiert','Alle Zeilen der Tabelle werden geändert','Es gibt einen Syntaxfehler','Nur die erste Zeile wird geändert'], c:1, e:'Ohne WHERE betrifft UPDATE die komplette Tabelle — Vorsicht!'},
    {q:'Was passiert bei DELETE FROM tabelle ohne WHERE?', o:['Die Tabelle wird komplett gelöscht (DROP)','Alle Zeilen werden gelöscht, die Tabelle bleibt aber bestehen','Nichts, DELETE braucht immer WHERE','Nur doppelte Zeilen werden gelöscht'], c:1, e:'DELETE ohne WHERE leert die Tabelle, im Gegensatz zu DROP TABLE bleibt die Struktur erhalten.'},
    {q:'Was ist eine Transaktion?', o:['Ein einzelnes SELECT','Eine Folge von Operationen, die als Ganzes erfolgreich oder gar nicht ausgeführt wird','Ein Backup','Ein Index'], c:1, e:'Transaktionen garantieren: alles oder nichts.'},
    {q:'Wofür steht das A in ACID?', o:['Access','Atomicity (Atomarität) — alles oder nichts','Availability','Aggregation'], c:1, e:'Atomicity: eine Transaktion wird ganz oder gar nicht ausgeführt.'},
    {q:'Wofür steht das C in ACID?', o:['Consistency (Konsistenz) — DB bleibt in gültigem Zustand','Cache','Concurrency','Compression'], c:0, e:'Consistency: die Datenbank bleibt vor und nach der Transaktion konsistent.'},
    {q:'Wofür steht das I in ACID?', o:['Integration','Isolation — parallele Transaktionen beeinflussen sich nicht unkontrolliert','Index','Insertion'], c:1, e:'Isolation trennt gleichzeitig laufende Transaktionen voneinander ab.'},
    {q:'Wofür steht das D in ACID?', o:['Deletion','Durability (Dauerhaftigkeit) — Änderungen bleiben nach COMMIT erhalten','Data','Distribution'], c:1, e:'Durability: nach einem COMMIT übersteht die Änderung sogar einen Absturz.'},
    {q:'Was macht ROLLBACK?', o:['Speichert die Transaktion dauerhaft','Macht alle Änderungen der aktuellen Transaktion rückgängig','Löscht die Tabelle','Erstellt eine neue Transaktion'], c:1, e:'ROLLBACK setzt die Transaktion auf den Stand vor dem START TRANSACTION zurück.'},
  ],
  w7: [
    {q:'Wofür steht NoSQL?', o:['No Structured Query Language','Not only SQL — Datenbanken jenseits des klassischen relationalen Modells','Kein SQL erlaubt','Neue SQL-Version'], c:1, e:'"Not only SQL" — ergänzt relationale Datenbanken für bestimmte Anwendungsfälle.'},
    {q:'Wann greift man eher zu NoSQL statt relational?', o:['Bei kleinen, stabilen Datenmengen mit strikten Beziehungen','Bei sehr großen, schnell wachsenden Datenmengen mit horizontaler Skalierung','Nie, NoSQL ist immer schlechter','Nur für Textdateien'], c:1, e:'NoSQL punktet bei Massendaten, hoher Schreiblast und horizontaler Skalierung.'},
    {q:'Merkmal eines Key-Value-Stores?', o:['Daten als einfache Schlüssel-Wert-Paare, sehr schneller Zugriff über den Key','Knoten und Kanten','Tabellen mit festen Spalten','Nur für Bilder geeignet'], c:0, e:'Sehr simples, aber extrem schnelles Modell — ideal für Sessions, Caches.'},
    {q:'Merkmal eines Wide-Column-Stores?', o:['Spaltenorientiert, flexible Spalten pro Zeile, gut für riesige strukturierte Datenmengen','Nur Schlüssel-Wert-Paare','Ausschließlich Graphen','Ausschließlich Dokumente'], c:0, e:'Z. B. Cassandra — jede Zeile kann unterschiedliche Spalten haben.'},
    {q:'Merkmal eines Document-Stores?', o:['Speichert Dokumente (z. B. JSON), Struktur kann je Dokument variieren','Speichert nur Zahlen','Erzwingt striktes, festes Schema','Kennt keine Verschachtelung'], c:0, e:'Z. B. MongoDB — jedes Dokument kann eigene Felder haben.'},
    {q:'Merkmal einer Graphdatenbank?', o:['Speichert Knoten und Kanten — ideal für stark vernetzte Daten und Beziehungsabfragen','Speichert nur flache Tabellen','Kennt keine Beziehungen','Ist immer am schnellsten für einfache Lookups'], c:0, e:'Z. B. Neo4j — optimiert für Fragen wie "Freunde von Freunden".'},
    {q:'Scale-up vs. Scale-out?', o:['Scale-up = stärkere Hardware für einen Server; Scale-out = mehr Server parallel','Beides bedeutet dasselbe','Scale-out = ein größerer Server','Scale-up = mehr Server'], c:0, e:'Scale-out (horizontale Skalierung) ist die Stärke vieler NoSQL-Systeme.'},
    {q:'Was besagt BASE (Gegenmodell zu ACID)?', o:['Basically Available, Soft state, Eventually consistent','Backup Always Saves Everything','Binary Atomic Secure Encryption','Balanced Automatic Storage Engine'], c:0, e:'BASE toleriert vorübergehende Inkonsistenz zugunsten von Verfügbarkeit und Skalierung.'},
    {q:'Was besagt das CAP-Theorem?', o:['Man kann von Consistency, Availability, Partition Tolerance höchstens 2 gleichzeitig voll garantieren','Alle drei sind immer gleichzeitig möglich','CAP betrifft nur relationale Datenbanken','CAP hat mit Verteilung nichts zu tun'], c:0, e:'Bei einer Netzwerkpartition muss man zwischen Konsistenz und Verfügbarkeit wählen.'},
  ],
};

/* ---------- Boss-Fragen je Welt (schwerer, gemischt) ---------- */
const BOSS = {
  w1: [
    {q:'Tabelle SCHÜLER(schueler_id, name, klasse). Welche Spalte ist der beste Kandidat für den Primärschlüssel?', o:['name','klasse','schueler_id','Keine, alle drei zusammen'], c:2, e:'schueler_id ist eindeutig und ändert sich nicht — idealer PK. Namen können doppelt vorkommen.'},
    {q:'Warum ist "name" allein meist ein schlechter Primärschlüssel?', o:['Namen sind zu kurz','Namen können bei mehreren Personen gleich sein','Namen sind immer NULL','SQL erlaubt keine Text-Primärschlüssel'], c:1, e:'Zwei Personen können denselben Namen haben — der PK muss aber eindeutig sein.'},
    {q:'Eine Spalte "email" soll pro Kunde eindeutig, aber nicht der Primärschlüssel sein. Welcher Constraint passt?', o:['NOT NULL','UNIQUE','PRIMARY KEY','FOREIGN KEY'], c:1, e:'UNIQUE erzwingt Eindeutigkeit, ohne die Spalte zum PK zu machen.'},
    {q:'Was passiert, wenn eine Fremdschlüssel-Spalte auf eine nicht existierende Zeile zeigen würde?', o:['Das ist erlaubt und normal','Referenzielle Integrität wird verletzt — DBMS verhindert das i. d. R.','Die Datenbank löscht automatisch die Zeile','Nichts, Fremdschlüssel sind nur Kommentare'], c:1, e:'FOREIGN KEY Constraints schützen genau davor.'},
    {q:'Zwei Tabellen ohne jede Verbindung (kein FK) — was fehlt aus Modellierungssicht meist?', o:['Nichts, das ist normal','Vermutlich eine fehlende Beziehung/Fremdschlüssel, falls sie fachlich zusammengehören','Ein Index','Ein zweiter Primärschlüssel'], c:1, e:'Fachlich zusammengehörige Tabellen sollten i. d. R. über FKs verbunden sein.'},
    {q:'Was ist der Unterschied zwischen Attribut und Domäne?', o:['Attribut = Spalte, Domäne = erlaubter Wertebereich dieser Spalte','Kein Unterschied','Domäne = Tabelle, Attribut = Datenbank','Attribut ist immer eine Zahl'], c:0, e:'Die Domäne schränkt ein, welche Werte ein Attribut annehmen darf.'},
  ],
  w2: [
    {q:'"Ein Land hat eine Hauptstadt, eine Stadt ist Hauptstadt von genau einem Land" — Kardinalität + Umsetzung?', o:['n:m, Verknüpfungstabelle','1:1, Fremdschlüssel (evtl. UNIQUE)','1:n, kein Fremdschlüssel nötig','Keine Beziehung nötig'], c:1, e:'1:1-Beziehung — ein Fremdschlüssel reicht, UNIQUE sichert die Eindeutigkeit ab.'},
    {q:'Ein Mitarbeiter kann in mehreren Projekten mitarbeiten, ein Projekt hat mehrere Mitarbeiter. Wie viele zusätzliche Tabellen braucht die Umsetzung mindestens?', o:['Keine','Eine Verknüpfungstabelle mit zwei Fremdschlüsseln','Zwei zusätzliche Tabellen','Drei zusätzliche Tabellen'], c:1, e:'n:m braucht genau eine Verknüpfungstabelle (z. B. MITARBEIT(mitarbeiter_id, projekt_id)).'},
    {q:'RECHNUNGSPOSITION hängt von RECHNUNG ab und hat ohne sie keinen Sinn — was ist RECHNUNGSPOSITION?', o:['Eine starke Entität','Eine schwache Entität','Ein Attribut','Eine Domäne'], c:1, e:'Schwache Entitäten existieren nur im Kontext einer starken Entität.'},
    {q:'Warum braucht eine n:m-Verknüpfungstabelle meist einen zusammengesetzten Primärschlüssel?', o:['Weil das Zufall ist','Weil die Kombination beider Fremdschlüssel die Zeile eindeutig macht','Weil SQL das verlangt, egal was','Verknüpfungstabellen brauchen nie einen PK'], c:1, e:'z. B. (bestellung_id, artikel_id) zusammen sind eindeutig, jede Spalte allein nicht unbedingt.'},
    {q:'Kardinalität "0..1 zu 0..n" bei KUNDE–BESTELLUNG bedeutet:', o:['Jeder Kunde hat genau eine Bestellung','Ein Kunde kann keine, eine oder mehrere Bestellungen haben; jede Bestellung gehört zu genau einem Kunden','Jede Bestellung gehört zu mehreren Kunden','Kunden und Bestellungen sind nicht verbunden'], c:1, e:'0..1 auf Kundenseite würde heißen: die Bestellung hat 0 oder 1 Kunden. Hier: 0..n Bestellungen je Kunde.'},
    {q:'Ein ER-Modell wird in Tabellen überführt. Was wird aus einer 1:n-Beziehung typischerweise?', o:['Eine eigene Verknüpfungstabelle','Ein Fremdschlüssel auf der "n"-Seite, der auf den PK der "1"-Seite zeigt','Zwei neue Primärschlüssel','Gar nichts, 1:n wird ignoriert'], c:1, e:'Die "n"-Seite bekommt den Fremdschlüssel (z. B. BESTELLUNG.kunde_id).'},
  ],
  w3: [
    {q:'Tabelle BESTELLUNG(bestellung_id, kunde_id, kundenname, kundenort) — welches Problem liegt vor?', o:['1NF verletzt','Redundanz/3NF-Problem: kundenname und kundenort hängen nicht vom Schlüssel bestellung_id ab, sondern von kunde_id','Kein Problem','2NF verletzt, weil PK zusammengesetzt ist'], c:1, e:'kundenname/-ort sind transitiv über kunde_id abhängig — gehören in eine eigene KUNDE-Tabelle.'},
    {q:'Tabelle BESTELLPOSITION(bestellung_id, artikel_id, menge, artikelname) mit PK (bestellung_id, artikel_id) — welches Problem?', o:['3NF-Verletzung durch transitive Abhängigkeit über einen Nicht-Schlüssel','2NF-Verletzung: artikelname hängt nur von artikel_id ab, nicht vom vollen Schlüssel','1NF-Verletzung','Kein Problem'], c:1, e:'Partielle Abhängigkeit vom zusammengesetzten Schlüssel — klassische 2NF-Verletzung.'},
    {q:'Eine Spalte "telefonnummern" enthält "0664-123, 0680-456" in einer Zelle. Welche Normalform ist verletzt?', o:['1NF — Werte sind nicht atomar','2NF','3NF','Keine'], c:0, e:'Mehrere Werte in einer Zelle verletzen die 1NF (Atomaritätsforderung).'},
    {q:'Eine Tabelle ist in 3NF. Was folgt daraus über 1NF und 2NF?', o:['Nichts, das sind unabhängige Regeln','3NF setzt 1NF und 2NF bereits voraus — sie sind automatisch erfüllt','Sie verletzt automatisch 1NF','3NF ist schwächer als 1NF'], c:1, e:'Die Normalformen bauen aufeinander auf: 3NF ⟹ 2NF ⟹ 1NF.'},
    {q:'Warum lohnt sich Normalisierung manchmal NICHT vollständig (z. B. aus Performance-Gründen)?', o:['Sie ist immer schlecht','Stark normalisierte Schemata brauchen mehr JOINs, was Abfragen verlangsamen kann — daher wird manchmal bewusst denormalisiert','Normalisierung ist in SQL verboten','Es gibt keinen Grund, sie zu vermeiden'], c:1, e:'Denormalisierung ist ein bewusster Kompromiss zwischen Redundanzfreiheit und Lesegeschwindigkeit.'},
    {q:'Welche Anomalie liegt vor: "Lösche ich Bestellung 3, verschwindet die einzige Information, dass Kunde Max Novak existiert"?', o:['Einfügeanomalie','Änderungsanomalie','Löschanomalie','Keine, das ist normal'], c:2, e:'Mit der Bestellung geht ungewollt auch die Kundeninformation verloren.'},
  ],
  w4: [
    {q:'Onlineshop: ARTIKEL und FILM (Subklasse mit Zusatzfeldern wie fsk, laufzeit) sollen per Joined Table Inheritance modelliert werden. Wie sind die Tabellen verbunden?', o:['Gar nicht, zwei getrennte Welten','FILM hat denselben Primärschlüssel wie den zugehörigen ARTIKEL, zugleich Fremdschlüssel auf ARTIKEL','FILM enthält alle Artikel-Spalten dupliziert','ARTIKEL enthält alle Film-Spalten'], c:1, e:'Klassisches Joined-Table-Pattern: FILM.artikel_id ist PK und gleichzeitig FK auf ARTIKEL.'},
    {q:'Welche Vererbungsstrategie erzeugt die meisten NULL-Werte?', o:['Table per Class','Single Table Inheritance','Joined Table Inheritance','Keine erzeugt NULL-Werte'], c:1, e:'Bei einer gemeinsamen Tabelle für alle Subklassen bleiben nicht-passende Spalten NULL.'},
    {q:'Welche Vererbungsstrategie braucht bei einer Abfrage über die Basisklasse KEINEN JOIN?', o:['Joined Table Inheritance','Single Table Inheritance','Beide brauchen immer einen JOIN','Table per Class braucht nie einen JOIN'], c:1, e:'Bei Single Table Inheritance liegt alles in einer Tabelle — kein JOIN nötig, dafür viele NULLs.'},
    {q:'Ein Constraint verlangt: "Jede Bestellung muss zu einem existierenden Kunden gehören." Welcher Constraint-Typ?', o:['UNIQUE','NOT NULL','FOREIGN KEY','CHECK'], c:2, e:'FOREIGN KEY erzwingt referenzielle Integrität zwischen Tabellen.'},
    {q:'Für ein Attribut "geburtsdatum" — welcher Datentyp ist am passendsten?', o:['VARCHAR','DATE','BOOLEAN','INT'], c:1, e:'DATE speichert Kalenderdaten korrekt und erlaubt Datumsvergleiche/-rechnung.'},
    {q:'Nachteil von Table per Class (Concrete Table Inheritance)?', o:['Zu wenige Tabellen','Gemeinsame Spalten (z. B. Name, Preis) werden in jeder Subklassen-Tabelle dupliziert','Zu viele NULL-Werte','Kein Nachteil vorhanden'], c:1, e:'Gemeinsame Struktur wiederholt sich in jeder Tabelle — Änderungen müssen überall gepflegt werden.'},
  ],
  w5: [
    {q:'NATURAL JOIN zwischen zwei Tabellen, die zufällig beide eine Spalte "ort" haben (fachlich unterschiedliche Bedeutung) — was droht?', o:['Ein Syntaxfehler','Ein ungewollter zusätzlicher/falscher Verknüpfungsversuch über "ort" — meist weniger/falsche Zeilen im Ergebnis','Das Ergebnis ist garantiert korrekt','NATURAL JOIN ignoriert gleichnamige Spalten automatisch'], c:1, e:'NATURAL JOIN verknüpft automatisch über ALLE gleichnamigen Spalten — eine Falle bei zufällig gleichen Namen.'},
    {q:'UNION zweier SELECTs schlägt fehl — wahrscheinlichster Grund?', o:['Zu viele Zeilen','Unterschiedliche Anzahl oder unpassende Typen der Spalten in beiden SELECTs','UNION braucht immer ORDER BY','Beide SELECTs nutzen dieselbe Tabelle'], c:1, e:'UNION verlangt spaltenweise passende Struktur (Anzahl & kompatible Typen).'},
    {q:'SELECT kategorie, COUNT(*) FROM ARTIKEL GROUP BY kategorie HAVING COUNT(*) > 2 — was liefert das?', o:['Alle Artikel einzeln','Nur Kategorien mit mehr als 2 Artikeln, mit ihrer Anzahl','Nur Kategorien mit genau 2 Artikeln','Einen Fehler, weil HAVING verboten ist'], c:1, e:'HAVING filtert nach der Gruppierung anhand des Aggregatwerts COUNT(*).'},
    {q:'Eine View wurde mit JOIN und Aggregatfunktion definiert. Ein UPDATE auf die View wird versucht — was passiert typischerweise?', o:['Funktioniert problemlos wie bei einer normalen Tabelle','Meist ein Fehler oder Einschränkung, da nicht eindeutig auf Basistabellen abbildbar','Löscht automatisch alle Basistabellen','Erstellt automatisch eine neue Tabelle'], c:1, e:'Views mit JOIN/GROUP BY/Aggregaten sind i. d. R. nicht (vollständig) schreibbar.'},
    {q:'LEFT JOIN KUNDE → BESTELLUNG: Ein Kunde ohne Bestellung — was steht in den BESTELLUNG-Spalten dieser Zeile?', o:['0','Leerstring','NULL','Die Zeile fehlt komplett'], c:2, e:'Fehlende Treffer werden bei LEFT JOIN mit NULL aufgefüllt, die Kundenzeile bleibt aber erhalten.'},
    {q:'INTERSECT zweier Abfragen liefert:', o:['Alle Zeilen aus beiden zusammen','Nur Zeilen, die in BEIDEN Ergebnissen vorkommen','Nur Zeilen, die NUR in der ersten Abfrage vorkommen','Immer eine leere Menge'], c:1, e:'INTERSECT = Schnittmenge der beiden Ergebnismengen.'},
  ],
  w6: [
    {q:'Zwei Transaktionen lesen denselben Kontostand, beide berechnen unabhängig einen neuen Wert und schreiben ihn — eine Änderung geht verloren. Welches Phänomen?', o:['Dirty Read','Lost Update','Phantom Read','Non-repeatable Read'], c:1, e:'Lost Update: eine der beiden Schreiboperationen überschreibt die andere ungewollt.'},
    {q:'Transaktion A liest einen noch nicht committeten Wert von Transaktion B, die danach ein ROLLBACK macht. Welches Phänomen?', o:['Dirty Read','Lost Update','Phantom Read','Serialisierungsfehler'], c:0, e:'Dirty Read: gelesen wird ein Wert, der nie "offiziell" existiert hat.'},
    {q:'Transaktion A liest eine Zeile zweimal und bekommt beide Male unterschiedliche Werte, weil B zwischendurch committet hat. Welches Phänomen?', o:['Dirty Read','Non-repeatable Read','Phantom Read','Lost Update'], c:1, e:'Non-repeatable Read: derselbe Datensatz ändert sich zwischen zwei Lesevorgängen innerhalb einer Transaktion.'},
    {q:'Transaktion A zählt Zeilen mit einer Bedingung zweimal und bekommt beim zweiten Mal mehr Zeilen, weil B neue eingefügt hat. Welches Phänomen?', o:['Phantom Read','Dirty Read','Lost Update','Kein Phänomen, das ist normal'], c:0, e:'Phantom Read: neue passende Zeilen "erscheinen" zwischen zwei Abfragen.'},
    {q:'Welches Isolationslevel verhindert ALLE vier klassischen Phänomene (inkl. Phantom Read)?', o:['Read Uncommitted','Read Committed','Repeatable Read','Serializable'], c:3, e:'Serializable ist das strengste Isolationslevel.'},
    {q:'Warum kostet ein hohes Isolationslevel (z. B. Serializable) oft Performance?', o:['Es kostet nichts','Mehr Sperren/Kontrollen nötig, um Nebenläufigkeits-Phänomene zu verhindern → weniger Parallelität möglich','Es nutzt weniger Speicher','Es braucht keine Transaktionen mehr'], c:1, e:'Strengere Isolation bedeutet mehr Koordinationsaufwand zwischen parallelen Transaktionen.'},
  ],
  w7: [
    {q:'Ein Onlineshop will Produktbewertungen mit stark wechselnden Feldern je Produktkategorie speichern (mal Größe, mal Laufzeit, mal ...). Welcher NoSQL-Typ passt am besten?', o:['Key-Value-Store','Document-Store','Graphdatenbank','Wide-Column-Store'], c:1, e:'Dokumente mit flexibler, variabler Struktur sind die Stärke von Document-Stores.'},
    {q:'Ein soziales Netzwerk will "Freunde 3. Grades" in Millisekunden finden. Welcher NoSQL-Typ passt am besten?', o:['Key-Value-Store','Wide-Column-Store','Graphdatenbank','Document-Store'], c:2, e:'Graphdatenbanken sind für tief vernetzte Beziehungsabfragen optimiert.'},
    {q:'Ein IoT-System speichert Milliarden Sensormesswerte, meist spaltenweise über Zeit ausgewertet. Welcher NoSQL-Typ passt am besten?', o:['Wide-Column-Store','Graphdatenbank','Key-Value-Store','Relationale DB ist hier immer besser'], c:0, e:'Wide-Column-Stores wie Cassandra sind für riesige, spaltenorientierte Zeitreihen gebaut.'},
    {q:'Warum kann "Eventual Consistency" bei einem verteilten System sinnvoll sein?', o:['Weil Inkonsistenz immer gut ist','Weil sie Verfügbarkeit/Performance zugunsten sofortiger globaler Konsistenz priorisiert — für viele Anwendungsfälle ausreichend','Weil ACID dadurch garantiert wird','Weil dadurch keine Replikation nötig ist'], c:1, e:'Eventual Consistency toleriert kurzzeitige Abweichungen zwischen Knoten, um Verfügbarkeit/Geschwindigkeit zu gewinnen.'},
    {q:'Nach dem CAP-Theorem: Bei einer Netzwerkpartition muss ein System wählen zwischen…', o:['Consistency und Availability','Nur Performance','Backup und Restore','SQL und NoSQL'], c:0, e:'Partition Tolerance ist bei verteilten Systemen meist gesetzt — die Wahl fällt zwischen C und A.'},
    {q:'Warum ist horizontale Skalierung (Scale-out) bei vielen NoSQL-Systemen leichter als bei klassischen relationalen DBs?', o:['NoSQL-Daten sind grundsätzlich kleiner','Viele NoSQL-Modelle verzichten bewusst auf komplexe JOINs/Transaktionen über mehrere Server hinweg, was Verteilung vereinfacht','Relationale DBs können grundsätzlich nicht auf mehreren Servern laufen','Es gibt keinen echten Unterschied'], c:1, e:'Der Verzicht auf serverübergreifende JOINs/starke Konsistenz erleichtert die Verteilung auf viele Server.'},
  ],
};

/* ---------- Match-Pools je Welt (Begriffe/Szenario ↔ Zuordnung) ---------- */
const MATCH = {
  w1: [
    {a:'Primärschlüssel', b:'Eindeutige, nicht leere Kennung jeder Zeile'},
    {a:'Fremdschlüssel', b:'Verweist auf den Primärschlüssel einer anderen Tabelle'},
    {a:'Tupel / Zeile', b:'Ein einzelner Datensatz in einer Tabelle'},
    {a:'Attribut / Spalte', b:'Eine Eigenschaft, die jede Zeile besitzt'},
    {a:'Relation', b:'Fachbegriff für eine Tabelle'},
    {a:'Domäne', b:'Menge der erlaubten Werte eines Attributs'},
    {a:'Kardinalität', b:'Gibt an, wie viele Zeilen zweier Tabellen miteinander verknüpft sein können'},
    {a:'DBMS', b:'Software, die die Datenbank verwaltet und Abfragen ausführt'},
  ],
  w2: [
    {a:'Eine Person hat einen Reisepass, ein Reisepass gehört einer Person', b:'1 : 1'},
    {a:'Ein Kunde tätigt mehrere Bestellungen', b:'1 : n'},
    {a:'Ein Film hat mehrere Schauspieler, ein Schauspieler spielt in mehreren Filmen', b:'n : m'},
    {a:'Ein Land hat eine Hauptstadt', b:'1 : 1'},
    {a:'Eine Bestellung enthält mehrere Artikel, ein Artikel steht in mehreren Bestellungen', b:'n : m'},
    {a:'Ein Mitarbeiter gehört zu einer Abteilung, eine Abteilung hat mehrere Mitarbeiter', b:'1 : n'},
    {a:'Ein Schüler besucht mehrere Kurse, ein Kurs hat mehrere Schüler', b:'n : m'},
    {a:'Ein Auto hat genau ein Kennzeichen', b:'1 : 1'},
  ],
  w3: [
    {a:'Ein Attribut enthält mehrere Telefonnummern kommagetrennt', b:'1NF verletzt (keine atomaren Werte)'},
    {a:'Artikelname hängt nur von einem Teil des zusammengesetzten Schlüssels ab', b:'2NF verletzt (partielle Abhängigkeit)'},
    {a:'Ort hängt von PLZ ab, PLZ ist Nicht-Schlüssel-Attribut', b:'3NF verletzt (transitive Abhängigkeit)'},
    {a:'Löscht man die letzte Bestellung, verschwindet auch der Kundenname', b:'Löschanomalie'},
    {a:'Der Kundenname muss bei jeder Bestellung neu eingegeben werden', b:'Redundanz'},
    {a:'Ohne eine Bestellung kann kein neuer Artikel erfasst werden', b:'Einfügeanomalie'},
    {a:'Die Adresse ändert sich und muss in 50 Zeilen aktualisiert werden', b:'Änderungsanomalie'},
    {a:'Atomare Werte, voll funktional & nicht transitiv abhängig', b:'3NF erfüllt'},
  ],
  w4: [
    {a:'INT', b:'Ganze Zahl, z. B. eine ID'},
    {a:'VARCHAR(n)', b:'Zeichenkette variabler Länge bis n Zeichen'},
    {a:'DECIMAL', b:'Exakte Zahl mit Nachkommastellen, z. B. ein Preis'},
    {a:'DATE', b:'Datumswert (Jahr-Monat-Tag)'},
    {a:'BOOLEAN', b:'Wahrheitswert true/false'},
    {a:'PRIMARY KEY', b:'Eindeutige, nicht leere Kennung einer Zeile'},
    {a:'FOREIGN KEY', b:'Verweis auf den Primärschlüssel einer anderen Tabelle'},
    {a:'NOT NULL', b:'Spalte darf keinen leeren Wert enthalten'},
  ],
  w7: [
    {a:'Session-Daten eines Webshops, blitzschneller Zugriff per ID', b:'Key-Value-Store'},
    {a:"Soziales Netzwerk: 'Freunde von Freunden' finden", b:'Graphdatenbank'},
    {a:'Produktkatalog mit stark unterschiedlichen Attributen je Artikel', b:'Document-Store'},
    {a:'Sensordaten von Millionen Geräten, spaltenweise über die Zeit ausgewertet', b:'Wide-Column-Store'},
    {a:'Warenkorb, der nur per eindeutiger ID gelesen wird', b:'Key-Value-Store'},
    {a:'Empfehlungen basierend auf Beziehungen zwischen Nutzern und Produkten', b:'Graphdatenbank'},
    {a:'Blog-Artikel mit optionalen, wechselnden Feldern', b:'Document-Store'},
    {a:'Zeitreihendaten von IoT-Sensoren in riesigem Umfang', b:'Wide-Column-Store'},
  ],
};

const WORLDS = [
  {id:'w1', n:1, title:'Datenbank-Basics', sub:'Tabellen, Schlüssel, Begriffe', icon:'🗂️', color:'s', skillType:'match'},
  {id:'w2', n:2, title:'ER-Modell', sub:'Entitäten, Beziehungen, Kardinalitäten', icon:'🕸️', color:'k', skillType:'match'},
  {id:'w3', n:3, title:'Normalisierung', sub:'1NF · 2NF · 3NF, Anomalien', icon:'🧹', color:'a', skillType:'match'},
  {id:'w4', n:4, title:'Tabellen & Vererbung', sub:'CREATE TABLE, Constraints, Strategien', icon:'🏗️', color:'b', skillType:'match'},
  {id:'w5', n:5, title:'SQL-Abfragen', sub:'SELECT, JOIN, GROUP BY, Views', icon:'🔎', color:'s', skillType:'sql'},
  {id:'w6', n:6, title:'Transaktionen', sub:'INSERT/UPDATE/DELETE, ACID', icon:'⚡', color:'warn', skillType:'sql'},
  {id:'w7', n:7, title:'NoSQL', sub:'Key-Value, Document, Graph & Co.', icon:'🌐', color:'k', skillType:'match'},
];

if(typeof module !== 'undefined' && module.exports){
  module.exports = {SEED_DB, SQL_TASKS_W5, SQL_TASKS_W6, QUIZ, BOSS, MATCH, WORLDS, SQL_CHEATSHEET};
}
